//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusuario
    {
        public int idUsuario { get; set; }
        public string loginUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string claveUsuario { get; set; }
        public System.DateTime fechaCreacionUsuario { get; set; }
        public System.DateTime fechaModificacionUsuario { get; set; }
    }
}
